private: false

subPackages:
  - frontend

docker:
  build:
    defaultTag: latest
    autoTags: [main, latest, next]

docs:
  location: docs

  logo: false

  types: {}

  externalTypes:
    - https://softvisio-node.github.io/core/
    - https://softvisio-node.github.io/result/

  aliases:
    /api: https://raw.githubusercontent.com/softvisio-node/core/main/docs/api.md

  app:
    api:
      url: wss://localhost/api
    rpc:
      url: ws://localhost/api
