env:
  APP_PUSH_TOPIC: devel

  APP_SITE_URL: http://localhost/

  APP_DB: pgsql://<NAME>:1@devel
  # APP_CLUSTER: redis://devel/0?namespace=<NAME>
  # APP_SERVICE_datasets: ws://devel:10000?cacheReset=disconnect&cacheReset=event/update

  # root
  APP_ROOT_PASSWORD: 1
  APP_ROOT_EMAIL: admin@softvisio.net

  # smtp
  APP_SMTP_FROM: no-reply [devel] "no-reply@softvisio.net"
  APP_SMTP_HOSTNAME: smtp.gmail.com
  APP_SMTP_PORT: 465
  APP_SMTP_USERNAME: no-reply@softvisio.net
  APP_SMTP_PASSWORD: ~
