env:
  APP_PUSH_TOPIC: release
  APP_DB: pgsql://<NAME>:<PASWORD>@pgsql
  APP_CLUSTER: redis://redis/0
  APP_CLUSTER_NAMESPACE: <NAME>
  # APP_SERVICE_databases: ws://databases:8080

root:
  password: ~
  email: admin@softvisio.net

settings:
  app_url: http://localhost/

  # SMTP
  smtp_from: no-reply "no-reply@softvisio.net"
  smtp_hostname: smtp.gmail.com
  smtp_port: 465
  smtp_username: no-reply@softvisio.net
  smtp_password: ~

  # TELEGRAM BOT
  telegram_bot_name: ~
  telegram_bot_key: ~
  telegram_bot_enabled: false
  telegram_signin_enabled: false
