FROM ghcr.io/zerocluster/node

LABEL org.opencontainers.image.source="https://github.com/OWNER/REPO"

RUN \
    # install deps
    npm i --omit=dev \
    \
    # build app
    && pushd app \
    && NODE_ENV= npm i \
    && npm run build \
    && mv www /tmp && rm -rf * && mv /tmp/www . \
    && popd \
    \
    # cleanup
    && curl -fsSL https://raw.githubusercontent.com/softvisio/scripts/main/env-build-node.sh | /bin/bash -s -- cleanup
