#!/usr/bin/env -S docker stack deploy --with-registry-auth NAME -c

version: "3.9"

# NOTE deploy
# docker stack deploy --with-registry-auth -c docker-stack.yaml NAME

services:
  NAME:
    image: softvisio/NAME

    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 3
      labels:
        nginx.server-name: app.domain, api.domain, dev.domain
        nginx.client-max-body-size: 10m
        nginx.cache: "true"
        nginx.cache.max-size: 10g
        nginx.cache.inactive: 1w

    configs:
      - { source: .env.yaml, target: /var/local/dist/data/.env.yaml }
      - { source: .env.production.yaml, target: /var/local/dist/data/.env.production.yaml }

    networks: [private]

    volumes:
      - { type: volume, source: maxmind, target: /var/lib/maxmind }

    init: true
    stop_grace_period: 5m
    shm_size: 1g

    build:
      context: .

configs:
  .env.yaml: { file: data/.env.yaml }
  .env.production.yaml: { file: data/.env.production.yaml }

networks:
  private: { external: true }

volumes:
  maxmind: { external: true }

x-build:
  default_tag: latest
  auto_tags: [main, devel, latest]
  # tags_mapping: { main: latest }
